# Generated by Django 2.2.4 on 2020-12-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_auto_20201213_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='authors',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='authors',
            name='Notes',
            field=models.TextField(default=''),
        ),
    ]
